# Generated by Django 5.0.2 on 2024-02-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="colaborators",
            name="nivel",
            field=models.CharField(
                choices=[("G", "Gerente"), ("B", "Bancario")], default="B", max_length=1
            ),
        ),
    ]
