# Generated by Django 5.0.2 on 2024-02-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0010_alter_colaborators_nivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
