# Generated by Django 5.0.2 on 2024-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0015_alter_customuser_options_alter_colaborators_nivel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborators",
            name="nivel",
            field=models.CharField(
                choices=[("G", "Gerente"), ("B", "Bancario")], default="B", max_length=1
            ),
        ),
    ]
