# Generated by Django 5.0.2 on 2024-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0017_alter_colaborators_nivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborators",
            name="nivel",
            field=models.CharField(
                choices=[("G", "Gerente"), ("B", "Bancario")], default="B", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
