# Generated by Django 5.0.2 on 2024-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0018_alter_colaborators_nivel_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
