# Generated by Django 5.0.2 on 2024-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bank", "0019_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": [("can_do_something", "Can do something")]},
        ),
        migrations.AlterField(
            model_name="colaborators",
            name="nivel",
            field=models.CharField(
                choices=[("B", "Bancario"), ("G", "Gerente")], default="B", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_groups",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_permissions",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
