# Generated by Django 5.0.2 on 2024-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0023_alter_colaborators_nivel_alter_customuser_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborators",
            name="nivel",
            field=models.CharField(
                choices=[("G", "Gerente"), ("C", "Colaborator")],
                default="B",
                max_length=1,
            ),
        ),
    ]
